### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [nfourtythree/entriessubset#18]
Wondering if this plugin will get updated for Craft 4?

**Comment by nfourtythree** [comment]
Hi @angieherrera 

Just pushed version 2.0 of the plugin which is the compatibility update for Craft CMS v4.

It is worth noting now that native Entries fields have the "Selectable Entries Condition" setting, that condition builder provides a good portion of the functionality that this plugin does.

The only thing that is maybe lacking at the moment is that the Entry Type condition only allows the selection of a single entry type (unlike this plugin that allows you to select multiple).

In Craft CMS v4.1 that restriction is being lifted and you will be able to select multiple Entry Types.

I give all this information as it is worth evaluating your usage of this plugin to see if it might be possible to just use the native functionality that comes with Craft.

Thanks!

**Comment by angieherrera** [comment]
Awesome, thanks so much for the detailed update!
