### ISSUE TITLE
Craft 5

### ISSUE THREAD

**Issue by johannesSolvr** [nfourtythree/entriessubset#31]
Hi,

Will this be updated to Craft CMS 5?

**Comment by headerlocation** [comment]
Hi @nfourtythree,

I would also like to know if it will be updated for Craft 5.

**Comment by nfourtythree** [comment]
Hi All

My sincere apologies that this is way, _way_, overdue. 

Have just pushed version `3.0.0` which is the Craft 5 compatible version.

To get this version, change your `nfourtythree/entriessubset` requirement in your project's `composer.json` to:

```json
"require": {
  "nfourtythree/entriessubset": "^3.0.0",
  "...": "..."
}
```

Then run `composer update`.

The functionality in this plugin is almost all covered natively now in Craft and although it is nice for people to be using this I think everyone would prefer if they could achieve their goals without the need for an extra plugin.

I would look to get the final missing pieces add to Craft core and then Entries Subset and happily ride off into retirement. 🌄

Thanks!
